---
title: "Quality Control"
author: "Drake Williams"
date: "`r BiocStyle::doc_date()`"
output: html_document
knit: (function(inputFile, encoding) { 
    rmarkdown::render(
        inputFile, encoding = encoding, 
        output_file = file.path(
            dirname(inputFile), paste0('02_QC_',Sys.Date(),'.html'))) 
                })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = F,
  message = F, 
  out.width = "100%",
  fig.align = "center"
)
options(width = 1200)
```

# Introduction

The objective of this notebook is to perform quality control to filter out 'poor quality' cells from further analysis.

## Load packages

```{r load packages}
library(pacman)
p_load(Seurat, scCustomize, dplyr)
```

## Load datasets and metadata
```{r load datasets}
combined <- readRDS(file = "/home/williamsdrw/epithelial-IL23/04_data_objects/01_SoupX_objects/2023-05-27_015-allWithMeta.RDS")
```


## Cell filtering and plotting 

### all samples
```{r all QC, fig.height=40, fig.width=40}
combined <- Add_Mito_Ribo_Seurat(combined, species = "human", overwrite = T)
combined <- PercentageFeatureSet(combined, "^HB", col.name = "percent_hb")
VlnPlot(combined,
  features = c(
    "nCount_RNA",
    "nFeature_RNA",
    "percent_mito",
    "percent_ribo",
    "percent_hb"),
  pt.size = 0,
  ncol = 2, 
  group.by = "orig.ident"
) +
  NoLegend()

# filter out spots with few features, high mito and high blood contamination
# this removes the actual spot from analysis
print(paste0("Number of cells pre-QC: ", dim(combined)))
combined <- combined[, combined$nFeature_RNA > 100 & combined$nFeature_RNA < 5000 & combined$percent_mito < 20 & combined$percent_hb < 75]
print(paste0("Number of cells post-QC: ", dim(combined)))

# look at top genes to see if any specific need to be filtered out of analysis
C <- combined@assays$RNA@counts
C@x <- C@x / rep.int(
  colSums(C),
  diff(C@p)
)
most_expressed <- order(Matrix::rowSums(C),
  decreasing = T
)[20:1]
boxTable <- t(as.matrix(C[most_expressed, ]))
boxplot(boxTable,
  cex = 0.1,
  las = 1,
  xlab = "% total count per cell",
  col = (scales::hue_pal())(20)[20:1],
  horizontal = TRUE
)

# mito genes seem to be the most pervasive so filter those out
# this only removes the gene from consideration, not spots that contain those genes
print(dim(combined))
combined <- combined[!grepl("MALAT1", rownames(combined)), ]
combined <- combined[!grepl("^MT-", rownames(combined)), ]
combined <- combined[!grepl("^RP[L|S]", rownames(combined)), ]
combined <- combined[!grepl("^HB-", rownames(combined)), ]
print(dim(combined))

C <- combined@assays$RNA@counts
C@x <- C@x / rep.int(
  colSums(C),
  diff(C@p)
)
most_expressed <- order(Matrix::rowSums(C),
  decreasing = T
)[20:1]
boxTable <- t(as.matrix(C[most_expressed, ]))
boxplot(boxTable,
  cex = 0.1,
  las = 1,
  title = "Post-QC",
  xlab = "% total count per cell",
  col = (scales::hue_pal())(20)[20:1],
  horizontal = TRUE
)

```


## Save new objects
```{r save objects}
baseDir <- "~/epithelial-IL23/04_data_objects/02_QC_objects/"
saveRDS(combined, file = paste0(baseDir, Sys.Date(), "_02-QCOutput.RDS"))
```

## Session Info
```{r session info}
sessionInfo()
```
