---
title: "Clustering"
author: "Drake Williams"
date: "`r BiocStyle::doc_date()`"
output: html_document
knit: (function(inputFile, encoding) { 
    rmarkdown::render(
        inputFile, encoding = encoding, 
        output_file = file.path(
            dirname(inputFile), paste0('03_Integration_',Sys.Date(),'.html'))) 
                })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = F,
  message = F, 
  message = F,
  out.width = "100%",
  fig.align = "center"
)
options(width = 1200)
```

# Introduction

The objective of this notebook is to perform clustering and identify cell types present in the dataset

## Load packages

```{r load packages}
library(pacman)
p_load(Seurat,dplyr,scCustomize, ggplot2,pheatmap)
```

## Load datasets
```{r load datasets}
baseDir <- "~/updatedAtlas-hu/04_data_objects/03_Analysis_objects/"
oralIntegrated <- readRDS(file = paste0(baseDir, "2023-04-27_03-IntegrationOutput.RDS"))

```

## Cluster cells

```{r cc regression and clustering}
## Cell-cycle scoring and regression
s.genes <- cc.genes.updated.2019$s.genes
g2m.genes <- cc.genes.updated.2019$g2m.genes
oralIntegrated <- CellCycleScoring(oralIntegrated,
  s.features = s.genes, g2m.features = g2m.genes,
  set.ident = TRUE
)
oralIntegrated <- ScaleData(oralIntegrated, vars.to.regress = c("S.Score", "G2M.Score"), verbose = TRUE)

# Follow typical workflow
oralIntegrated <- RunPCA(oralIntegrated, verbose = FALSE)
oralIntegrated <- FindNeighbors(oralIntegrated, dims = 1:50)
oralIntegrated <- FindClusters(oralIntegrated, verbose = FALSE, resolution = 1)
oralIntegrated <- RunUMAP(oralIntegrated, dims = 1:50)
```
## Generate lists of marker genes for clustered cells
```{r visualize clusters, fig.width=8, fig.height=8}
DimPlot_scCustom(seurat_object = oralIntegrated, split.by = "ref")
DimPlot_scCustom(seurat_object = oralIntegrated, group.by = "ref", shuffle=T, figure_plot=T)
DimPlot_scCustom(seurat_object = oralIntegrated, group.by = "seurat_clusters", shuffle=T, figure_plot=T)

# Assuming your Seurat object is named "oralIntegrated"
ref_groups <- unique(oralIntegrated@meta.data$ref)

# Calculate the number of cells in each cluster that belong to each 'ref' group
cluster_ref_counts <- table(Idents(oralIntegrated), oralIntegrated@meta.data$ref)

# Calculate the percentage of cells in each cluster that belong to each 'ref' group
cluster_ref_percents <- as.data.frame(cluster_ref_counts) %>% 
  group_by(Var1) %>% 
  mutate(percent = Freq / sum(Freq) * 100)

# Generate a bar graph for each cluster
for (cluster_id in unique(Idents(oralIntegrated))) {
  cluster_percents <- cluster_ref_percents[cluster_ref_percents$Var1 == cluster_id,]
  print(ggplot(cluster_percents, aes(x = Var2, y = percent)) +
    geom_bar(stat = "identity") +
    xlab("ref group") +
    ylab("percentage of cells") +
    ggtitle(paste("Cluster", cluster_id)) +
    theme_minimal())
}
# Generate a single plot with a facet for each cluster
ggplot(cluster_ref_percents, aes(x = Var2, y = percent)) +
  geom_bar(stat = "identity") +
  xlab("ref group") +
  ylab("percentage of cells") +
  facet_wrap(~Var1, ncol = 5) +
  theme_minimal()

# Calculate the percentage of cells in each cluster that belong to each 'ref' group
percentages <- prop.table(table(Idents(oralIntegrated), oralIntegrated$ref), margin = 1) * 100

# Create a heat map of the percentages
pheatmap(percentages, cluster_cols = FALSE, scale = "row", main = "Cluster percentages by ref group")

```
## Generate lists of marker genes for clustered cells
```{r cluster markers}
# Set appropriate assay and cluster level that will enable identification of RBC/all groups
DefaultAssay(oralIntegrated) <- "RNA"
Idents(oralIntegrated) <- "integrated_snn_res.1"

# Find cluster defining markers
all.markers.1 <- FindAllMarkers(oralIntegrated, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.75)
significant.markers.1 <- all.markers.1[all.markers.1$p_val_adj < 0.2, ]
# Print some top markers
significant.markers.1 %>%
  group_by(cluster) %>%
  top_n(n = 5, wt = avg_log2FC)
# Save top markers
top.markers.1 <- significant.markers.1 %>%
  group_by(cluster) %>%
  top_n(n = 30, wt = avg_log2FC)
baseDir <- "~/updatedAtlas-hu/07_csv_outputs/"
write.csv(top.markers.1, paste0(baseDir, Sys.Date(), "_top30_res1.csv"))
```

## Save new objects
```{r save objects}
baseDir <- "~/updatedAtlas-hu/04_data_objects/03_Analysis_objects/"
saveRDS(oralIntegrated,
  file = paste0(
    baseDir,
    Sys.Date(),
    "_04_01-ClusteringOutput.RDS"
  )
)
```

## Session Info
```{r session info}
sessionInfo()
```
