---
title: "STAT1 GOF Analysis"
author: "Drake Williams"
date: "`r BiocStyle::doc_date()`"
output: html_document
knit: (function(inputFile, encoding) { 
    rmarkdown::render(
        inputFile, encoding = encoding, 
        output_file = file.path(
            dirname(inputFile), paste0('05_01_STAT1-Analysis_',Sys.Date(),'.html'))) 
                })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = F,
  message = F,
  message = F,
  out.width = "100%",
  fig.align = "center"
)
options(width = 1200)
```

# Objective

Exploration of STAT1 GOF patient scSeq data

## todo
Compare H v P v S (no tx)
Compare Pre and Post TOFA
Add type 17 scores/genes
Heatmap instead of VlnPlot

## Load packages

```{r load packages}
library(pacman)
p_load(Seurat, scCustomize, patchwork, data.table, ggplot2)
```

## Load datasets

```{r load datasets}
baseDir <- "~/updatedAtlas-hu/04_data_objects/03_Analysis_objects/"
oralIntegrated <- readRDS(file = paste0(baseDir, "2023-04-29_04_02-AnnotationOutput.RDS"))
```

## Clean up dataset to include only relevant samples

```{r subset data}
# # subset only data from our lab
# Idents(oralIntegrated) <- "ref"
# oralIntegrated <- subset(oralIntegrated,
#   idents = c("Williams 2021")
# )

# update status metadata to include stat1 and treatment info
# read meta file from patient DB
metaToAdd <- read.csv(file = "~/10x_samples.csv")
# get current seurat obj metadata
currentMeta <- oralIntegrated@meta.data
# select relevant metadata columns from the patient DB file
colsToKeep <- names(metaToAdd)[c(1, 10)]
metaToAdd <- metaToAdd[, names(metaToAdd) %in% colsToKeep]
# select rows in the patient DB file that correspond to samples used in seurat obj
metaToAdd <- metaToAdd[metaToAdd$Sample.ID %in% unique(currentMeta$orig.ident), ]
# rename some columns
names(metaToAdd)[names(metaToAdd) == "Sample.ID"] <- "orig.ident"
# add the metadata using scCustomize function
fwrite(metaToAdd, file = paste0(
  getwd(), "/03_meta_data/",
  Sys.Date(),
  "metaToAdd.csv"
))

oralIntegrated <- Add_Sample_Meta(oralIntegrated,
  meta_data = paste0(
    getwd(),
    "/03_meta_data/",
    Sys.Date(),
    "metaToAdd.csv"
  ),
  join_by_meta = "orig.ident",
  join_by_seurat = "orig.ident",
  overwrite = T
)
# check/confirm the structure of the seurat object metadata
unique(oralIntegrated$status)

Idents(oralIntegrated) <- "status"
oralIntegrated <- subset(oralIntegrated,
  idents = c("L-UST", "H", "P"),
  invert = T
)

oralIntegrated$status2 <- oralIntegrated@active.ident
genes <- list(c("CXCL10", "CXCL11", "APOL6", "SAMD9L", "BATF2", "GBP4", "EPSTI1", "STAT1", "CXCL9", "IDO1", "WARS1"))
oralIntegrated <- AddModuleScore(object = oralIntegrated, features = genes, name = "IFN_score")
```


```{r visualize UMAPs, fig.height=7, fig.width=10}
DimPlot_scCustom(oralIntegrated,
  group.by = "fineCellTypes",
  split.by = "orig.ident",
  colors_use = oralIntegrated@misc$fineCellPal_colors
)

DimPlot_scCustom(oralIntegrated,
  group.by = "generalCellTypes",
  split.by = "orig.ident",
  colors_use = oralIntegrated@misc$fineCellPal_colors
)
```
```{r, fig.height=20, fig.width=20, eval = F}
# check variable features in S_Rx and S_NoRx
st <- subset(oralIntegrated, idents = "S-tofa")
st <- FindVariableFeatures(st)
sr <- subset(oralIntegrated, idents = "S-ruxo")
sr <- FindVariableFeatures(sr)
snrx <- subset(oralIntegrated, idents = "S")
snrx <- FindVariableFeatures(snrx)
h <- subset(oralIntegrated, idents = "H")
h <- FindVariableFeatures(h)
p <- subset(oralIntegrated, idents = "P")
p <- FindVariableFeatures(p)

a <- VariableFeaturePlot_scCustom(
  seurat_object = h, num_features = 20, repel = TRUE,
  y_axis_log = TRUE
)
b <- VariableFeaturePlot_scCustom(
  seurat_object = p, num_features = 20, repel = TRUE,
  y_axis_log = TRUE
)
c <- VariableFeaturePlot_scCustom(
  seurat_object = snrx, num_features = 20, repel = TRUE,
  y_axis_log = TRUE
)
d <- VariableFeaturePlot_scCustom(
  seurat_object = sr, num_features = 20, repel = TRUE,
  y_axis_log = TRUE
)
e <- VariableFeaturePlot_scCustom(
  seurat_object = st, num_features = 20, repel = TRUE,
  y_axis_log = TRUE
)
(a | b) / (c | plot_spacer()) / (d | e) + plot_layout(guides = "collect")
```
```{r, fig.width=12, fig.height=6, eval = F}
a <- Plot_Density_Custom(seurat_object = h, features = c("STAT1", "IFNG"))
b <- Plot_Density_Custom(seurat_object = p, features = c("STAT1", "IFNG"))
c <- Plot_Density_Custom(seurat_object = snrx, features = c("STAT1", "IFNG"))
d <- Plot_Density_Custom(seurat_object = sr, features = c("STAT1", "IFNG"))
e <- Plot_Density_Custom(seurat_object = st, features = c("STAT1", "IFNG"))
(a | b) / (c | plot_spacer()) / (d | e)

```
```{r}
split <- SplitObject(oralIntegrated, split.by = "orig.ident")
lapply(X = split, FUN = function(x) {
    Plot_Density_Custom(x, features = c("IFNG"))
    })
lapply(X = split, FUN = function(x) {
    Plot_Density_Custom(x, features = c("STAT1"))
    })
# b <- Plot_Density_Custom(seurat_object = p, features = c("STAT1", "IFNG"))
# c <- Plot_Density_Custom(seurat_object = snrx, features = c("STAT1", "IFNG"))
# d <- Plot_Density_Custom(seurat_object = sr, features = c("STAT1", "IFNG"))
# e <- Plot_Density_Custom(seurat_object = st, features = c("STAT1", "IFNG"))
# (a | b) / (c | plot_spacer()) / (d | e)

```
```{r, fig.width=12, fig.height=12}
patch <- FeaturePlot_scCustom(
  seurat_object = oralIntegrated,
  features = "IFN_score1",
  split.by = "orig.ident",
  combine = F
)
(patch[[1]] | patch[[2]]) / (patch[[3]] | plot_spacer()) / (patch[[4]] | patch[[5]])
  plot_layout(ncol = 2, guides = "collect")
```

```{r, fig.height=12, fig.width=12}
# compare expression based on sex
# bulk <- AggregateExpression(oralIntegrated, return.seurat = T, slot = "counts", assays = "RNA", group.by = c(
#   "generalCellTypes",
#   "orig.ident", "status"
# ))
# 
# bulk$celltype <- sapply(strsplit(Cells(bulk), split = "_"), "[", 1)
# bulk$donor <- sapply(strsplit(Cells(bulk), split = "_"), "[", 2)
# bulk$status <- sapply(strsplit(Cells(bulk), split = "_"), "[", 3)
# Idents(bulk) <- "status"
# bulk$status <- factor(x = bulk$status, levels = c("H", "P", "S", "ruxo", "tofa"))
# 
# myel <- subset(bulk, celltype == "Myeloid")
# Idents(myel) <- "status"
# de_markers <- FindMarkers(myel, ident.1 = "S", ident.2 = "ruxo", slot = "counts", test.use = "wilcox",
#     verbose = T)
# de_markers$gene <- rownames(de_markers)
# ggplot(de_markers, aes(avg_log2FC, -log10(p_val))) + geom_point(size = 0.5, alpha = 0.5) + theme_bw() +
#     ylab("-log10(unadjusted p-value)") + geom_text_repel(aes(label = ifelse(p_val_adj < 0.05, gene,
#     "")), colour = "red", size = 3)
#
# fib2 <- subset(bulk, celltype == "Fibroblast 2")
# Idents(fib2) <- "status"
# de_markers <- FindMarkers(fib2, ident.1 = "H", ident.2 = "P", slot = "counts", test.use = "wilcox",
#     verbose = F)
# de_markers$gene <- rownames(de_markers)
# ggplot(de_markers, aes(avg_log2FC, -log10(p_val))) + geom_point(size = 0.5, alpha = 0.5) + theme_bw() +
#     ylab("-log10(unadjusted p-value)") + geom_text_repel(aes(label = ifelse(p_val_adj < 0.05, gene,
#     "")), colour = "red", size = 3)
# Idents(bulk) <- "celltype"
# VlnPlot_scCustom(bulk,
#   features = genes[[1]],
#   pt.size = 2,
#   colors_use = c("#BB0021FF", "#5F559BFF", "#EFC000FF", "#808180FF", "#1B1919FF"),
#   idents = c("Myeloid"),
#   group.by = "status"
# ) +
#   theme(
#     axis.title.x = element_blank(),
#     axis.text.x = element_text(angle = 0, vjust = 1, hjust = 0.5)
#   )
# VlnPlot_scCustom(bulk,
#   features = genes[[1]],
#   pt.size = 2,
#   colors_use = c("#BB0021FF", "#5F559BFF", "#EFC000FF", "#808180FF", "#1B1919FF"),
#   idents = c("Fibroblast"),
#   group.by = "status"
# ) +
#   theme(
#     axis.title.x = element_blank(),
#     axis.text.x = element_text(angle = 0, vjust = 1, hjust = 0.5)
#   )
# VlnPlot_scCustom(bulk,
#   features = genes[[1]],
#   pt.size = 2,
#   colors_use = c("#BB0021FF", "#5F559BFF", "#EFC000FF", "#808180FF", "#1B1919FF"),
#   idents = c("Lymphoid (T/NK)"),
#   group.by = "status"
# ) +
#   theme(
#     axis.title.x = element_blank(),
#     axis.text.x = element_text(angle = 0, vjust = 1, hjust = 0.5)
#   )


# Stacked_VlnPlot(bulk,
#   features = genes[[1]],
#   x_lab_rotate = T,
#   colors_use = c(
#     "#BB0021FF",
#     "#5F559BFF",
#     "#EFC000FF",
#     "#808180FF",
#     "#1B1919FF"
#   ),
#   split.by = "status",
#   plot_legend = T
# )
Stacked_VlnPlot(oralIntegrated,
  features = genes[[1]],
  x_lab_rotate = T,
  colors_use = c(
    "#BB0021FF",
    "#5F559BFF",
    "#EFC000FF",
    "#808180FF",
    "#1B1919FF"
  ),
  group.by = "fineCellTypes",
  split.by = "orig.ident",
  plot_legend = T
)
```
```{r}
Clustered_DotPlot(seurat_object = oralIntegrated, features = genes[[1]], k = 4, exp_color_min = 0, group.by = "orig.ident")
```

```{r}
sessionInfo()
```
